string_data = {
    "PTT": "批踢踢",
    "PTT2": "批踢踢兔",
    "active": "啟動",
    "author": "作者",
    "board": "看板",
    "can_not_use_search_post_code_f": "此狀態下無法使用搜尋文章代碼(AID)功能",
    "catch_bottom_post": "取得置底文章",
    "change_pw": "變更密碼",
    "comment": "推文",
    "comment_content": "推文內文",
    "comment_date": "推文日期",
    "comment_id": "推文帳號",
    "connect": "連線",
    "connect_core": "連線核心",
    "connect_fail": "連線失敗",
    "connect_mode_TELNET": "Telnet",
    "connect_mode_WEBSOCKET": "WebSocket",
    "connection_closed": "連線已經被關閉",
    "content": "內文",
    "current_version": "目前版本",
    "date": "日期",
    "delete_post": "刪除文章",
    "development_version": "正在執行開發版本",
    "done": "完成",
    "english_module": "英文",
    "error_pw": "密碼不正確",
    "fail": "失敗",
    "find_newest_index": "找到最新編號",
    "get_board_info": "取得看板資訊 _target0_",
    "get_favourite_board_list": "取得我的最愛",
    "get_mail": "取得信件",
    "give_money_to": "給 _target0_ _target1_ P 幣",
    "goodbye": [
        "再見",
        "下次再見",
        "再會",
        "祝平安",
        "謝謝你，我很開心",
        "我們會再見面的"
    ],
    "has_comment_permission": "確認擁有推文權限",
    "has_new_mail_goto_main_menu": "有新信，回到主選單",
    "has_post_permission": "確認擁有貼文權限",
    "hide_sensitive_info": "隱藏敏感資訊",
    "in_login_process_please_wait": "登入中，請稍候",
    "initialization": "初始化",
    "kick_other_login": "強制執行剔除其他登入",
    "latest_version": "正在執行最新版本",
    "localhost": "本機",
    "login_fail": "登入失敗",
    "login_id": "登入帳號",
    "login_success": "登入 ... 成功",
    "login_too_often": "登入太頻繁",
    "logout": "登出",
    "mail_box_full": "郵件已滿",
    "mandarin_module": "繁體中文",
    "multi_thread_operate": "請勿使用多線程同時操作一個 PyPtt 物件",
    "must_be": "必須為",
    "must_be_a_boolean": "必須為布林值",
    "must_be_a_integer": "必須為數字",
    "must_be_a_string": "必須為字串",
    "must_between": "必須介於",
    "must_bigger_than": "必須大於",
    "must_small_than": "必須小於",
    "need_moderator_permission": "需要板主權限",
    "new_cursor": "新式游標",
    "new_version": "有新版本",
    "no_comment": "禁止推薦",
    "no_fast_comment": "禁止快速連續推文",
    "no_money": "PTT 幣不足",
    "no_permission": "使用者沒有權限",
    "no_response": "很抱歉, 此文章已結案並標記, 不得回應",
    "no_search_result": "沒有搜尋結果",
    "no_such_board": "無該看板",
    "no_such_mail": "無此信件",
    "no_such_post": "_target0_ 板找不到這個文章代碼 _target1_",
    "no_such_user": "無該使用者",
    "not_kick_other_login": "不剔除其他登入",
    "not_push_aligned": "無推文對齊",
    "not_record_ip": "不紀錄 IP",
    "old_cursor": "舊式游標",
    "only_secure_connection": "跳過填寫註冊單",
    "picks_in_register": "註冊申請單處理順位",
    "post": "發佈文章",
    "post_deleted": "文章已經被刪除",
    "prepare_connect_again": "準備再次連線",
    "ptt2_not_support": "批踢踢兔不支援此功能",
    "push_aligned": "推文對齊",
    "record_ip": "紀錄 IP",
    "reply_board": "回應至看板",
    "reply_board_mail": "回應至看板與作者信箱",
    "reply_mail": "回應至作者信箱",
    "require_login": "請先登入",
    "reset_your_contact_email": "請重新設定您的聯絡信箱",
    "retry": "重試",
    "search_user": "搜尋使用者",
    "send_mail": "寄信",
    "send_msg": "送出訊息",
    "set_connect_host": "設定連線主機",
    "set_connect_mode": "設定連線模式",
    "set_contact_mail_first": "請先設定聯絡信箱後才能修改密碼",
    "set_up_lang_module": "設定語言模組",
    "spend_time": "花費時間",
    "substandard_post": "不合規範文章",
    "success": "成功",
    "title": "標題",
    "transaction_cancelled": "交易取消!",
    "unregistered_user_cant_use_all_api": "未註冊使用者，將無法使用全部功能",
    "unregistered_user_cant_use_this_api": "未註冊使用者，無法使用此功能",
    "update_remote_version": "確認最新版本",
    "use_mailbox_api_will_logout_after_execution": "如果使用信箱相關功能，將執行後自動登出",
    "use_too_many_resources": "耗用過多資源",
    "user_has_previously_been_banned": "使用者之前已被禁言",
    "user_offline": "使用者離線",
    "wait_for_no_fast_comment": "因禁止快速連續推文，所以等待五秒",
    "welcome": "PyPtt v _target0_ 由 CodingMan 開發",
    "wrong_id_pw": "帳號密碼錯誤"
}
