string_data = {
    "PTT": "PTT",
    "PTT2": "PTT2",
    "active": "Active",
    "author": "Author",
    "board": "Board",
    "can_not_use_search_post_code_f": "This status can not use the search PostField code function",
    "catch_bottom_post_success": "Catch bottom post success",
    "change_pw": "Change password",
    "comment": "Comment",
    "comment_content": "Comment content",
    "comment_date": "Comment date",
    "comment_id": "Comment id",
    "connect": "Connect",
    "connect_core": "Connect core",
    "connect_fail": "Connect fail",
    "connect_mode_TELNET": "Telnet",
    "connect_mode_WEBSOCKET": "WebSocket",
    "connection_closed": "Connection Closed",
    "content": "Content",
    "current_version": "Current version",
    "date": "Date",
    "delete_post": "Delete post",
    "development_version": "Running development version",
    "done": "Done",
    "english_module": "English",
    "error_pw": "Wrong password",
    "fail": "Fail",
    "find_newest_index": "Find newest index",
    "get_board_info": "Get board info _target0_",
    "get_favourite_board_list": "Query favourite board list",
    "get_mail": "Get mail",
    "give_money_to": "give _target0_ _target1_ P coins",
    "goodbye": [
        "good bye",
        "bye",
        "see you",
        "catch you later",
        "I hate to run, but...",
        "Until we meet again, I will wait"
    ],
    "has_comment_permission": "User has permission to comment",
    "has_new_mail_goto_main_menu": "New mail! Back to main menu",
    "has_post_permission": "Have permission to post",
    "hide_sensitive_info": "Hide sensitive info",
    "in_login_process_please_wait": "In login process, please wait",
    "initialization": "Init",
    "kick_other_login": "Kick other login",
    "latest_version": "Running the latest version",
    "localhost": "Localhost",
    "login_fail": "Login fail",
    "login_id": "Login id",
    "login_success": "Login ... success",
    "login_too_often": "Login too often",
    "logout": "Logout",
    "mail_box_full": "Mail box is full",
    "mandarin_module": "Mandarin",
    "multi_thread_operate": "Do not use a multi-thread to operate a PyPtt object",
    "must_be": "Must be",
    "must_be_a_boolean": "Must be a boolean",
    "must_be_a_integer": "Must be a integer",
    "must_be_a_string": "Must be a string",
    "must_between": "Must between",
    "must_bigger_than": "Must bigger than",
    "must_small_than": "Must smaller than",
    "need_moderator_permission": "Need moderator permission",
    "new_cursor": "New cursor",
    "new_version": "There is a new version",
    "no_comment": "No comment",
    "no_fast_comment": "No fast comment",
    "no_money": "Not enough PTT coins",
    "no_permission": "User Has No Permission",
    "no_response": "This post has been closed and marked, no response",
    "no_search_result": "No Search Result",
    "no_such_board": "No such board",
    "no_such_mail": "No such mail",
    "no_such_post": "In _target0_, the post code is not EXISTS _target1_",
    "no_such_user": "No such user",
    "not_kick_other_login": "Not kick other login",
    "not_push_aligned": "No push aligned",
    "not_record_ip": "Not record IP",
    "old_cursor": "Old cursor",
    "only_secure_connection": "Skip registration form",
    "picks_in_register": "Registration application processing order",
    "post": "Post article",
    "post_deleted": "Post has been deleted",
    "prepare_connect_again": "Prepare connect again",
    "ptt2_not_support": "PTT2 not support this api",
    "push_aligned": "Push aligned",
    "record_ip": "Record ip",
    "reply_board": "Respond to the BoardField",
    "reply_board_mail": "Respond to the board and the mailbox of author",
    "reply_mail": "Respond to the mailbox of author",
    "require_login": "Please login first",
    "reset_your_contact_email": "Please reset your contact email",
    "retry": "Retry",
    "search_user": "Search user",
    "send_mail": "Send mail",
    "send_msg": "Send msg",
    "set_connect_host": "Set up the connect host",
    "set_connect_mode": "Set up the connect mode",
    "set_contact_mail_first": "Password can only be changed after setting the contact mailbox",
    "set_up_lang_module": "Set up language module",
    "spend_time": "Spend time",
    "substandard_post": "Substandard post",
    "success": "Success",
    "title": "Title",
    "transaction_cancelled": "The transaction is cancelled!",
    "unregistered_user_cant_use_all_api": "Unregistered UserField Can't Use All API",
    "unregistered_user_cant_use_this_api": "Unregistered UserField Can't Use This API",
    "update_remote_version": "Fetching latest version",
    "use_mailbox_api_will_logout_after_execution": "If you use mailbox related functions, you will be logged out automatically after execution",
    "use_too_many_resources": "Use too many resources",
    "user_has_previously_been_banned": "User has previously been banned",
    "user_offline": "User offline",
    "wait_for_no_fast_comment": "Because no fast comment, wait 5 sec",
    "welcome": "PyPtt v _target0_ developed by CodingMan",
    "wrong_id_pw": "Wrong id or pw"
}
