key = """-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIOc4AAV5EY78ok7x43oDn1btA7Kzsw/FpUEHfOGadEPQoAoGCCqGSM49
AwEHoUQDQgAESduZXH6HvYy/vhi570n5YspQKBEdBo6TjpVPR0cG+W6xAbWSifj8
I1ZnyK7L+MXMRWgPzCG6IsKltEFMPYIdSg==
-----END EC PRIVATE KEY-----
"""

cert = """-----BEGIN CERTIFICATE-----
MIICETCCAbegAwIBAgIUOiFG48mu+gVCb/nPvV/RMRsbc2EwCgYIKoZIzj0EAwIw
dzELMAkGA1UEBhMCVFcxDjAMBgNVBAgMBVN0YXRlMQ0wCwYDVQQHDARDaXR5MRUw
EwYDVQQKDAxPcmdhbml6YXRpb24xHDAaBgNVBAsME09yZ2FuaXphdGlvbmFsIFVu
aXQxFDASBgNVBAMMC0NvbW1vbiBOYW1lMB4XDTI0MDUwNTA1NDIxOVoXDTM0MDUw
MzA1NDIxOVowdzELMAkGA1UEBhMCVFcxDjAMBgNVBAgMBVN0YXRlMQ0wCwYDVQQH
DARDaXR5MRUwEwYDVQQKDAxPcmdhbml6YXRpb24xHDAaBgNVBAsME09yZ2FuaXph
dGlvbmFsIFVuaXQxFDASBgNVBAMMC0NvbW1vbiBOYW1lMFkwEwYHKoZIzj0CAQYI
KoZIzj0DAQcDQgAESduZXH6HvYy/vhi570n5YspQKBEdBo6TjpVPR0cG+W6xAbWS
ifj8I1ZnyK7L+MXMRWgPzCG6IsKltEFMPYIdSqMhMB8wHQYDVR0OBBYEFJJ8bcNm
nc61jcYoUMvbGN55CZRrMAoGCCqGSM49BAMCA0gAMEUCIEX8Q0CerrRdESybJPRO
NCQ8fNCbbbk6f3a9Wu9U6i4DAiEAoUTOQLf28Kw7RwH+URZVFLAdKaHFoCtlqcHE
Y8DQE/Q=
-----END CERTIFICATE-----
"""
