# NOTE: The cert / key below are a throwaway self-signed pair. They do not
# represent any identity — the subject is literally "CN=Common Name" and the
# pair is regenerated by scripts/gen_ssl.sh on every CI build.
#
# Why it exists: in some client environments (specific OpenSSL versions /
# middleboxes), the TLS handshake against wss://ws.ptt.cc fails when the
# client does not present any certificate. Presenting any self-signed cert
# avoids the failure path. PTT's server does not validate the contents of
# this cert, so the public private key here grants no privilege beyond
# what an anonymous client already has on a public BBS.
#
# The actual server-side TLS verification (CA bundle + hostname check) is
# performed in connect_core.ssl_init().

key = """-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIOc4AAV5EY78ok7x43oDn1btA7Kzsw/FpUEHfOGadEPQoAoGCCqGSM49
AwEHoUQDQgAESduZXH6HvYy/vhi570n5YspQKBEdBo6TjpVPR0cG+W6xAbWSifj8
I1ZnyK7L+MXMRWgPzCG6IsKltEFMPYIdSg==
-----END EC PRIVATE KEY-----
"""

cert = """-----BEGIN CERTIFICATE-----
MIICETCCAbegAwIBAgIUOiFG48mu+gVCb/nPvV/RMRsbc2EwCgYIKoZIzj0EAwIw
dzELMAkGA1UEBhMCVFcxDjAMBgNVBAgMBVN0YXRlMQ0wCwYDVQQHDARDaXR5MRUw
EwYDVQQKDAxPcmdhbml6YXRpb24xHDAaBgNVBAsME09yZ2FuaXphdGlvbmFsIFVu
aXQxFDASBgNVBAMMC0NvbW1vbiBOYW1lMB4XDTI0MDUwNTA1NDIxOVoXDTM0MDUw
MzA1NDIxOVowdzELMAkGA1UEBhMCVFcxDjAMBgNVBAgMBVN0YXRlMQ0wCwYDVQQH
DARDaXR5MRUwEwYDVQQKDAxPcmdhbml6YXRpb24xHDAaBgNVBAsME09yZ2FuaXph
dGlvbmFsIFVuaXQxFDASBgNVBAMMC0NvbW1vbiBOYW1lMFkwEwYHKoZIzj0CAQYI
KoZIzj0DAQcDQgAESduZXH6HvYy/vhi570n5YspQKBEdBo6TjpVPR0cG+W6xAbWS
ifj8I1ZnyK7L+MXMRWgPzCG6IsKltEFMPYIdSqMhMB8wHQYDVR0OBBYEFJJ8bcNm
nc61jcYoUMvbGN55CZRrMAoGCCqGSM49BAMCA0gAMEUCIEX8Q0CerrRdESybJPRO
NCQ8fNCbbbk6f3a9Wu9U6i4DAiEAoUTOQLf28Kw7RwH+URZVFLAdKaHFoCtlqcHE
Y8DQE/Q=
-----END CERTIFICATE-----
"""
