name: Test and Deploy

on:
  push:
    paths:
      - 'PyPtt/**/*'
      - 'setup.py'
      - 'requirements.txt'
      - 'docker/*'
    branches:
      - '**'
  pull_request:
    types:
      - opened
    paths:
      - 'PyPtt/**/*'
      - 'setup.py'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11", "3.12", "3.13", "3.13t", "3.14", "3.14t" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 PyPtt/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 PyPtt/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test
        run: |
          python -m pytest tests/test_init.py
          python -m pytest tests/test_i18n.py
          python -m pytest tests/test_exceptions.py
          python -m pytest tests/test_logger.py

  deploy:
    needs: test
    name: Deploy to PyPI and Docker
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          # Download PyPI information for version generation
          wget -q -O pypi_version.json https://pypi.org/pypi/PyPtt/json
      - name: Update SSL certificates
        run: |
          python3 scripts/gen_ssl.py
      - name: Build package
        run: |
          python -m build
      - name: Publish package to TestPyPI
        if: github.ref != 'refs/heads/master'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish package to PyPI
        if: github.ref == 'refs/heads/master'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Get package version
        id: get_version
        run: echo "PYPTT_VERSION=$(grep '__version__' PyPtt/__init__.py | cut -d"'" -f2)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set image name to lowercase
        id: image_name
        run: echo "NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image for master
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.image_name.outputs.NAME }}:latest
            ghcr.io/${{ steps.image_name.outputs.NAME }}:${{ env.PYPTT_VERSION }}
      - name: Sanitize branch name for Docker tag
        if: github.ref != 'refs/heads/master'
        id: sanitize_branch
        run: echo "TAG_SUFFIX=$(echo ${{ github.ref_name }} | sed 's/\//-/g')" >> $GITHUB_OUTPUT
      - name: Build and push Docker image for test branches
        if: github.ref != 'refs/heads/master'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.image_name.outputs.NAME }}:test-${{ steps.sanitize_branch.outputs.TAG_SUFFIX }}
